// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package mainproto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion7

// AuthClient is the client API for Auth service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AuthClient interface {
	GetLogListWithID(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*GetLogListWithIDResponse, error)
	CreateMacro(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*emptypb.Empty, error)
	GetMacroStatus(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*GetMacroStatusResponse, error)
	GetMacroSecret(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*GetMacroSecretResponse, error)
	ControlMacro(ctx context.Context, in *ControlMacroRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
}

type authClient struct {
	cc grpc.ClientConnInterface
}

func NewAuthClient(cc grpc.ClientConnInterface) AuthClient {
	return &authClient{cc}
}

func (c *authClient) GetLogListWithID(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*GetLogListWithIDResponse, error) {
	out := new(GetLogListWithIDResponse)
	err := c.cc.Invoke(ctx, "/main.Auth/GetLogListWithID", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authClient) CreateMacro(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, "/main.Auth/CreateMacro", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authClient) GetMacroStatus(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*GetMacroStatusResponse, error) {
	out := new(GetMacroStatusResponse)
	err := c.cc.Invoke(ctx, "/main.Auth/GetMacroStatus", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authClient) GetMacroSecret(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*GetMacroSecretResponse, error) {
	out := new(GetMacroSecretResponse)
	err := c.cc.Invoke(ctx, "/main.Auth/GetMacroSecret", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authClient) ControlMacro(ctx context.Context, in *ControlMacroRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, "/main.Auth/ControlMacro", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AuthServer is the server API for Auth service.
// All implementations must embed UnimplementedAuthServer
// for forward compatibility
type AuthServer interface {
	GetLogListWithID(context.Context, *emptypb.Empty) (*GetLogListWithIDResponse, error)
	CreateMacro(context.Context, *emptypb.Empty) (*emptypb.Empty, error)
	GetMacroStatus(context.Context, *emptypb.Empty) (*GetMacroStatusResponse, error)
	GetMacroSecret(context.Context, *emptypb.Empty) (*GetMacroSecretResponse, error)
	ControlMacro(context.Context, *ControlMacroRequest) (*emptypb.Empty, error)
	mustEmbedUnimplementedAuthServer()
}

// UnimplementedAuthServer must be embedded to have forward compatible implementations.
type UnimplementedAuthServer struct {
}

func (UnimplementedAuthServer) GetLogListWithID(context.Context, *emptypb.Empty) (*GetLogListWithIDResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetLogListWithID not implemented")
}
func (UnimplementedAuthServer) CreateMacro(context.Context, *emptypb.Empty) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateMacro not implemented")
}
func (UnimplementedAuthServer) GetMacroStatus(context.Context, *emptypb.Empty) (*GetMacroStatusResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetMacroStatus not implemented")
}
func (UnimplementedAuthServer) GetMacroSecret(context.Context, *emptypb.Empty) (*GetMacroSecretResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetMacroSecret not implemented")
}
func (UnimplementedAuthServer) ControlMacro(context.Context, *ControlMacroRequest) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ControlMacro not implemented")
}
func (UnimplementedAuthServer) mustEmbedUnimplementedAuthServer() {}

// UnsafeAuthServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AuthServer will
// result in compilation errors.
type UnsafeAuthServer interface {
	mustEmbedUnimplementedAuthServer()
}

func RegisterAuthServer(s grpc.ServiceRegistrar, srv AuthServer) {
	s.RegisterService(&Auth_ServiceDesc, srv)
}

func _Auth_GetLogListWithID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServer).GetLogListWithID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/main.Auth/GetLogListWithID",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServer).GetLogListWithID(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _Auth_CreateMacro_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServer).CreateMacro(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/main.Auth/CreateMacro",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServer).CreateMacro(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _Auth_GetMacroStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServer).GetMacroStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/main.Auth/GetMacroStatus",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServer).GetMacroStatus(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _Auth_GetMacroSecret_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServer).GetMacroSecret(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/main.Auth/GetMacroSecret",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServer).GetMacroSecret(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _Auth_ControlMacro_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ControlMacroRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServer).ControlMacro(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/main.Auth/ControlMacro",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServer).ControlMacro(ctx, req.(*ControlMacroRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Auth_ServiceDesc is the grpc.ServiceDesc for Auth service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Auth_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "main.Auth",
	HandlerType: (*AuthServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetLogListWithID",
			Handler:    _Auth_GetLogListWithID_Handler,
		},
		{
			MethodName: "CreateMacro",
			Handler:    _Auth_CreateMacro_Handler,
		},
		{
			MethodName: "GetMacroStatus",
			Handler:    _Auth_GetMacroStatus_Handler,
		},
		{
			MethodName: "GetMacroSecret",
			Handler:    _Auth_GetMacroSecret_Handler,
		},
		{
			MethodName: "ControlMacro",
			Handler:    _Auth_ControlMacro_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/main/main.proto",
}
