// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package mainproto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion7

// MainClient is the client API for Main service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type MainClient interface {
	GetLogListWithID(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*GetLogListWithIDResponse, error)
	CreateMacro(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*emptypb.Empty, error)
	GetMacroStatus(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*GetMacroStatusResponse, error)
	GetMacroSecret(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*GetMacroSecretResponse, error)
	ControlMacro(ctx context.Context, in *ControlMacroRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
}

type mainClient struct {
	cc grpc.ClientConnInterface
}

func NewMainClient(cc grpc.ClientConnInterface) MainClient {
	return &mainClient{cc}
}

func (c *mainClient) GetLogListWithID(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*GetLogListWithIDResponse, error) {
	out := new(GetLogListWithIDResponse)
	err := c.cc.Invoke(ctx, "/main.Main/GetLogListWithID", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mainClient) CreateMacro(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, "/main.Main/CreateMacro", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mainClient) GetMacroStatus(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*GetMacroStatusResponse, error) {
	out := new(GetMacroStatusResponse)
	err := c.cc.Invoke(ctx, "/main.Main/GetMacroStatus", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mainClient) GetMacroSecret(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*GetMacroSecretResponse, error) {
	out := new(GetMacroSecretResponse)
	err := c.cc.Invoke(ctx, "/main.Main/GetMacroSecret", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mainClient) ControlMacro(ctx context.Context, in *ControlMacroRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, "/main.Main/ControlMacro", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MainServer is the server API for Main service.
// All implementations must embed UnimplementedMainServer
// for forward compatibility
type MainServer interface {
	GetLogListWithID(context.Context, *emptypb.Empty) (*GetLogListWithIDResponse, error)
	CreateMacro(context.Context, *emptypb.Empty) (*emptypb.Empty, error)
	GetMacroStatus(context.Context, *emptypb.Empty) (*GetMacroStatusResponse, error)
	GetMacroSecret(context.Context, *emptypb.Empty) (*GetMacroSecretResponse, error)
	ControlMacro(context.Context, *ControlMacroRequest) (*emptypb.Empty, error)
	mustEmbedUnimplementedMainServer()
}

// UnimplementedMainServer must be embedded to have forward compatible implementations.
type UnimplementedMainServer struct {
}

func (UnimplementedMainServer) GetLogListWithID(context.Context, *emptypb.Empty) (*GetLogListWithIDResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetLogListWithID not implemented")
}
func (UnimplementedMainServer) CreateMacro(context.Context, *emptypb.Empty) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateMacro not implemented")
}
func (UnimplementedMainServer) GetMacroStatus(context.Context, *emptypb.Empty) (*GetMacroStatusResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetMacroStatus not implemented")
}
func (UnimplementedMainServer) GetMacroSecret(context.Context, *emptypb.Empty) (*GetMacroSecretResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetMacroSecret not implemented")
}
func (UnimplementedMainServer) ControlMacro(context.Context, *ControlMacroRequest) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ControlMacro not implemented")
}
func (UnimplementedMainServer) mustEmbedUnimplementedMainServer() {}

// UnsafeMainServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MainServer will
// result in compilation errors.
type UnsafeMainServer interface {
	mustEmbedUnimplementedMainServer()
}

func RegisterMainServer(s grpc.ServiceRegistrar, srv MainServer) {
	s.RegisterService(&Main_ServiceDesc, srv)
}

func _Main_GetLogListWithID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MainServer).GetLogListWithID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/main.Main/GetLogListWithID",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MainServer).GetLogListWithID(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _Main_CreateMacro_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MainServer).CreateMacro(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/main.Main/CreateMacro",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MainServer).CreateMacro(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _Main_GetMacroStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MainServer).GetMacroStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/main.Main/GetMacroStatus",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MainServer).GetMacroStatus(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _Main_GetMacroSecret_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MainServer).GetMacroSecret(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/main.Main/GetMacroSecret",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MainServer).GetMacroSecret(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _Main_ControlMacro_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ControlMacroRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MainServer).ControlMacro(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/main.Main/ControlMacro",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MainServer).ControlMacro(ctx, req.(*ControlMacroRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Main_ServiceDesc is the grpc.ServiceDesc for Main service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Main_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "main.Main",
	HandlerType: (*MainServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetLogListWithID",
			Handler:    _Main_GetLogListWithID_Handler,
		},
		{
			MethodName: "CreateMacro",
			Handler:    _Main_CreateMacro_Handler,
		},
		{
			MethodName: "GetMacroStatus",
			Handler:    _Main_GetMacroStatus_Handler,
		},
		{
			MethodName: "GetMacroSecret",
			Handler:    _Main_GetMacroSecret_Handler,
		},
		{
			MethodName: "ControlMacro",
			Handler:    _Main_ControlMacro_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/main/main.proto",
}
